[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Beam"

[font]
size = 14

[scrolling]
history = 20000

[selection]
save_to_clipboard = false

[shell]
args = ["--login"]
program = "/usr/bin/fish"

[window]
dynamic_title = false
opacity = 1
title = "terminal"

[window.dimensions]
columns = 120
lines = 34

[window.padding]
x = 12
y = 12
