add_newline = false
format = """
$time\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$python\
$lua\
$shell\
$rust\
$cmd_duration\
\n$character
"""

[package]
disabled = true

[line_break]
disabled = false

[time]
disabled = false
format = "[$time]($style)|"

[cmd_duration]
format = "[$duration]($style) "
